[features]
seeds = false
skip-lint = false
[programs.devnet]
etracker = "5TMCNvnK8FdXVLPdzH9SzRdULRNfHqAiqx5PmTCWpGkg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/bolt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
